{{- if .Values.services.apiGateway.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: api-gateway
  ports:
  - protocol: TCP
    port: {{ .Values.services.apiGateway.port }}
    targetPort: {{ .Values.services.apiGateway.targetPort }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  namespace: {{ .Values.global.namespace }}
  labels:
    app: api-gateway
    {{- include "microservice-application.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        {{- include "microservice-application.labels" . | nindent 8 }}
    spec:
      containers:
      - name: api-gateway-container
        image: "{{ .Values.global.image.repository }}:{{ .Values.services.apiGateway.image.tag }}"
        ports:
        - containerPort: {{ .Values.services.apiGateway.targetPort }}
        resources:
          {{- toYaml .Values.services.apiGateway.resources | nindent 10 }}
        envFrom:
        - configMapRef:
            name: {{ .Values.global.configMapName }}
{{- end }}